/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Ingreso extends javax.swing.JFrame {
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                   
    setLocationRelativeTo(null);
}  

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumno = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnRegistrarAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlumno.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Button - Liquid Glass - Text.png")); // NOI18N
        btnAlumno.setText("Alumno");
        btnAlumno.setBorderPainted(false);
        btnAlumno.setContentAreaFilled(false);
        btnAlumno.setFocusPainted(false);
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 120, 60));

        btnAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Button - Liquid Glass - Text (1).png")); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setBorderPainted(false);
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.setFocusPainted(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 110, 60));

        btnRegistrarAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Button - Liquid Glass - Text (2).png")); // NOI18N
        btnRegistrarAdmin.setText("Reg Admin");
        btnRegistrarAdmin.setBorderPainted(false);
        btnRegistrarAdmin.setContentAreaFilled(false);
        btnRegistrarAdmin.setFocusPainted(false);
        btnRegistrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 160, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\TIKTOK-RIZZ-ARMY-7-23-2025 2.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Utility Panel (1) (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoActionPerformed
          // TODO add your handling code here:
          new VerInasistencias().setVisible(true); // Abre la ventana VerInasistencias
    dispose(); 
    }//GEN-LAST:event_btnAlumnoActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
         new LoginAdmin().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnRegistrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAdminActionPerformed
        // TODO add your handling code here:
          new Registro().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnRegistrarAdminActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnRegistrarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
