/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;
import CapaLogica.*;
import CapaException.BDException;
import java.time.LocalDate;
import javax.swing.JOptionPane;


/**
 
 *
 * @author User
 */
public class RegistroInasistencia extends javax.swing.JFrame {
private void formWindowOpened(java.awt.event.WindowEvent evt) {                                   
    setLocationRelativeTo(null);
}  
    /**
     * Creates new form RegistroInasistencia
     */
    public RegistroInasistencia() {
        initComponents();
          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedulaDocente = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnGuardarDocente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnGuardarInasistencia = new javax.swing.JButton();
        spnHasta = new javax.swing.JSpinner();
        spnDesde = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Docente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 89, -1));
        jPanel1.add(txtCedulaDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 130, -1));

        btnGuardarDocente.setText("Guardar");
        btnGuardarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 160, -1));

        jLabel2.setText("Inasistencia:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 89, -1));

        jLabel3.setText("Desde:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 59, -1));

        jLabel4.setText("Hasta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 59, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnGuardarInasistencia.setText("Guardar");
        btnGuardarInasistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInasistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarInasistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 160, -1));

        spnHasta.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1761835567845L), null, null, java.util.Calendar.DAY_OF_MONTH));
        jPanel1.add(spnHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 140, -1));

        spnDesde.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1761662640000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        jPanel1.add(spnDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 140, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\image 4.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Untitled\\Form Contact (1) (1).png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 170, -1));

        jLabel10.setText("Apellido:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel8.setText("Cedula Docente:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel9.setText("Nombre");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Untitled\\Form Contact (1) (1).png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Untitled\\TIKTOK-RIZZ-ARMY-7-23-2025 2 (1).png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\1Figma\\Utility Panel (1) (1).png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDocenteActionPerformed
        // TODO add your handling code here:
        try {
        Docente d = new Docente(
            txtCedulaDocente.getText().trim(),
            txtNombre.getText().trim(),
            txtApellido.getText().trim()
        );
        new FachadaDocente().registrarDocente(d);
        JOptionPane.showMessageDialog(this, "Docente guardado correctamente.");
    } catch (BDException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_btnGuardarDocenteActionPerformed

    private void btnGuardarInasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInasistenciaActionPerformed
        // TODO add your handling code here:
       try {
        // 🔹 Obtener la fecha del spinner
        java.util.Date fechaD = (java.util.Date) spnDesde.getValue();
        java.util.Date fechaH = (java.util.Date) spnHasta.getValue();

        // 🔹 Crear la inasistencia (usa LocalDate si tu clase lo requiere)
        Inasistencia i = new Inasistencia(
            txtCedulaDocente.getText().trim(),
            new java.sql.Date(fechaD.getTime()).toLocalDate(),
            new java.sql.Date(fechaH.getTime()).toLocalDate()
        );

        // 🔹 Guardar en base de datos
        new FachadoInasistencia().registrarInasistencia(i);
        JOptionPane.showMessageDialog(this, "Inasistencia registrada correctamente.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnGuardarInasistenciaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
         dispose();
    new Ingreso().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroInasistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDocente;
    private javax.swing.JButton btnGuardarInasistencia;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnDesde;
    private javax.swing.JSpinner spnHasta;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedulaDocente;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
